version: 2.1
jobs:
  test:
    working_directory: ~/ci
    docker:
      # Primary container image where all steps run.
      - image: district0x/cljs-dev:latest
    steps:
      #- setup_remote_docker

      - checkout
      
      # Install Clojure Dependencies from Maven
      - run: lein deps

      # Install NodeJS Dependencies from NPM
      - run: lein npm install

      # Begin
      - run: make test-headless

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
